name: snap-sideloader
version: "0.1"
summary: Agent to sideload a snap installation
description: |
  Go web service to sideload snap installations
confinement: strict
grade: stable
base: core18

apps:
  run:
    command: bin/snap-sideloader
    daemon: simple
    plugs:
      - network
      - network-bind
      - snapd-control
      - home
      - removable-media

parts:
  application:
    plugin: go
    source: .
    source-type: git
    build-packages:
      - gcc
